// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBggjdjyQp5CzJkzLXKKnkUCirmmPfjfsc',
    appId: '1:571380933992:web:8832a8a441874d0ec522dd',
    messagingSenderId: '571380933992',
    projectId: 'jobfinder-e06f4',
    authDomain: 'jobfinder-e06f4.firebaseapp.com',
    storageBucket: 'jobfinder-e06f4.firebasestorage.app',
    measurementId: 'G-CT5ZVBTJDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANEKzzBTq59eXA3g2rdJRks3C-JxU8THE',
    appId: '1:571380933992:android:a03360f3c4cdc396c522dd',
    messagingSenderId: '571380933992',
    projectId: 'jobfinder-e06f4',
    storageBucket: 'jobfinder-e06f4.firebasestorage.app',
  );
}
